<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEqtlwaE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEqtlwaE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEqtlwaE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEqtlwaE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEqtlwaE\App_KernelDevDebugContainer([
    'container.build_hash' => 'EqtlwaE',
    'container.build_id' => '11e6aa97',
    'container.build_time' => 1733757925,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEqtlwaE');
